sudo: required
services:
  - docker

before_install:
  - docker build -t dzianismatveyenka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dzianismatveyenka/react-test npm test -- --coverage

after_success:
  - docker build -t dzianismatveyenka/multi-client ./client
  - docker build -t dzianismatveyenka/multi-nginx ./nginx
  - docker build -t dzianismatveyenka/multi-server ./server
  - docker build -t dzianismatveyenka/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dzianismatveyenka/multi-client
  - docker push dzianismatveyenka/multi-nginx
  - docker push dzianismatveyenka/multi-server
  - docker push dzianismatveyenka/multi-worker